name: main
description: "Aplicativo Lista de Tarefas"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  uuid: ^4.5.1
  sembast: ^3.5.0
  sembast_web: ^2.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

